spring.application.name=tvmaze-middleware
tvmaze.api.base-url=http://api.tvmaze.com
spring.data.mongodb.uri=mongodb+srv://jonfacundov_db_user:ts1yEb2HE9L789rB@middleware.wlfnesb.mongodb.net/tvmaze?appName=middleware
